//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.12.0
//     from Packages/com.walcht.ctvisualizer/Runtime/InputSystem/'UnityCTVisualizerInput'.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace UnityCTVisualizer
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.walcht.ctvisualizer/Runtime/InputSystem/'UnityCTVisualizerInput'.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @UnityCTVisualizerInput: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @UnityCTVisualizerInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""'UnityCTVisualizerInput'"",
    ""maps"": [
        {
            ""name"": ""VolumetricObjectControls"",
            ""id"": ""3331f265-8976-47ab-9358-5339ca680113"",
            ""actions"": [
                {
                    ""name"": ""Scale"",
                    ""type"": ""Value"",
                    ""id"": ""6073668b-178b-455d-90f6-acb3adc031c7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SlowScaleActivator"",
                    ""type"": ""Button"",
                    ""id"": ""5c824625-8ce3-486e-85c4-4791c161e4b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""469de6c6-daed-4279-80ec-b376e2e47bcb"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f035aff9-67cc-465d-b3e5-e9dedb58d738"",
                    ""path"": ""<Pointer>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scale"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""01ec5642-8f67-4c18-84c8-8b70804d6ce8"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlowScaleActivator"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // VolumetricObjectControls
            m_VolumetricObjectControls = asset.FindActionMap("VolumetricObjectControls", throwIfNotFound: true);
            m_VolumetricObjectControls_Scale = m_VolumetricObjectControls.FindAction("Scale", throwIfNotFound: true);
            m_VolumetricObjectControls_SlowScaleActivator = m_VolumetricObjectControls.FindAction("SlowScaleActivator", throwIfNotFound: true);
        }

        ~@UnityCTVisualizerInput()
        {
            UnityEngine.Debug.Assert(!m_VolumetricObjectControls.enabled, "This will cause a leak and performance issues, UnityCTVisualizerInput.VolumetricObjectControls.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // VolumetricObjectControls
        private readonly InputActionMap m_VolumetricObjectControls;
        private List<IVolumetricObjectControlsActions> m_VolumetricObjectControlsActionsCallbackInterfaces = new List<IVolumetricObjectControlsActions>();
        private readonly InputAction m_VolumetricObjectControls_Scale;
        private readonly InputAction m_VolumetricObjectControls_SlowScaleActivator;
        /// <summary>
        /// Provides access to input actions defined in input action map "VolumetricObjectControls".
        /// </summary>
        public struct VolumetricObjectControlsActions
        {
            private @UnityCTVisualizerInput m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public VolumetricObjectControlsActions(@UnityCTVisualizerInput wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "VolumetricObjectControls/Scale".
            /// </summary>
            public InputAction @Scale => m_Wrapper.m_VolumetricObjectControls_Scale;
            /// <summary>
            /// Provides access to the underlying input action "VolumetricObjectControls/SlowScaleActivator".
            /// </summary>
            public InputAction @SlowScaleActivator => m_Wrapper.m_VolumetricObjectControls_SlowScaleActivator;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_VolumetricObjectControls; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="VolumetricObjectControlsActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(VolumetricObjectControlsActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="VolumetricObjectControlsActions" />
            public void AddCallbacks(IVolumetricObjectControlsActions instance)
            {
                if (instance == null || m_Wrapper.m_VolumetricObjectControlsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_VolumetricObjectControlsActionsCallbackInterfaces.Add(instance);
                @Scale.started += instance.OnScale;
                @Scale.performed += instance.OnScale;
                @Scale.canceled += instance.OnScale;
                @SlowScaleActivator.started += instance.OnSlowScaleActivator;
                @SlowScaleActivator.performed += instance.OnSlowScaleActivator;
                @SlowScaleActivator.canceled += instance.OnSlowScaleActivator;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="VolumetricObjectControlsActions" />
            private void UnregisterCallbacks(IVolumetricObjectControlsActions instance)
            {
                @Scale.started -= instance.OnScale;
                @Scale.performed -= instance.OnScale;
                @Scale.canceled -= instance.OnScale;
                @SlowScaleActivator.started -= instance.OnSlowScaleActivator;
                @SlowScaleActivator.performed -= instance.OnSlowScaleActivator;
                @SlowScaleActivator.canceled -= instance.OnSlowScaleActivator;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="VolumetricObjectControlsActions.UnregisterCallbacks(IVolumetricObjectControlsActions)" />.
            /// </summary>
            /// <seealso cref="VolumetricObjectControlsActions.UnregisterCallbacks(IVolumetricObjectControlsActions)" />
            public void RemoveCallbacks(IVolumetricObjectControlsActions instance)
            {
                if (m_Wrapper.m_VolumetricObjectControlsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="VolumetricObjectControlsActions.AddCallbacks(IVolumetricObjectControlsActions)" />
            /// <seealso cref="VolumetricObjectControlsActions.RemoveCallbacks(IVolumetricObjectControlsActions)" />
            /// <seealso cref="VolumetricObjectControlsActions.UnregisterCallbacks(IVolumetricObjectControlsActions)" />
            public void SetCallbacks(IVolumetricObjectControlsActions instance)
            {
                foreach (var item in m_Wrapper.m_VolumetricObjectControlsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_VolumetricObjectControlsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="VolumetricObjectControlsActions" /> instance referencing this action map.
        /// </summary>
        public VolumetricObjectControlsActions @VolumetricObjectControls => new VolumetricObjectControlsActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "VolumetricObjectControls" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="VolumetricObjectControlsActions.AddCallbacks(IVolumetricObjectControlsActions)" />
        /// <seealso cref="VolumetricObjectControlsActions.RemoveCallbacks(IVolumetricObjectControlsActions)" />
        public interface IVolumetricObjectControlsActions
        {
            /// <summary>
            /// Method invoked when associated input action "Scale" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnScale(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SlowScaleActivator" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSlowScaleActivator(InputAction.CallbackContext context);
        }
    }
}
