BenchmarkingEventTypeEnumMapping = {
    "NEW_OPCAITY_CUTOFF_VALUE": 0,
    "NEW_SAMPLING_QUALITY_FACTOR_VALUE": 1,
    "NEW_INTERPOLATION_METHOD": 2,
    "NEW_RANDOM_ROTATION_AXIS": 3,
    "NEW_RANDOM_LOOK_AT_POINT": 4,
    "NEW_HOMOGENEITY_TOLERANCE_VALUE": 5,
    "NEW_LOD_QUALITY_FACTOR": 6,
    "BRICK_CACHE_WARMUP_START": 7,
    "BRICK_CACHE_WARMUP_END": 8,
    "FRAMETIMES_MEASUREMENTS_START": 9,
    "FRAMETIMES_MEASUREMENTS_END": 10,
    "FCT_MEASUREMENTS_START": 11,
    "FCT_MEASUREMENTS_END": 12,
}

InterpolationEnumMapping = {
    "NEAREST_NEIGHBOR": 0,
    "TRILLINEAR": 1,
}

RenderingModeEnumMapping = {
    "IC": 0,
    "OOC_PT": 1,
    "OOC_HYBRID": 2,
}
